//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "subscription")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub subscribed_user_id: i32,
    pub subscriber_user_id: i32,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::SubscriberUserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"    )]
    User2,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::SubscribedUserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User1,
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User1.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}